chore: makes progress standardizing our workflows (#33)

diff --git a/.github/workflows/manual_release.yml b/.github/workflows/manual_release.yml
--- a/.github/workflows/manual_release.yml
+++ b/.github/workflows/manual_release.yml
@@ -41,20 +41,28 @@ jobs:
         with:
           go-version: ${{ matrix.go-version }}
 
+      - name: Format
+        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
+
       - name: Install goimports
-        run: go get golang.org/x/tools/cmd/goimports
+        run: go install golang.org/x/tools/cmd/goimports@latest
 
       - run: goimports -l -w $(ls -d */*/ | grep -v "internal/protos/") ./momento
+
       - run: go mod tidy
-      # If there are any diffs from goimports or go mod tidy, fail.
+
+      - name: golangci-lint
+        uses: golangci/golangci-lint-action@v3
+        with:
+          version: latest
+          only-new-issues: true
+
+    # If there are any diffs from goimports or go mod tidy, fail.
       - name: Verify no changes from goimports and go mod tidy
         run: |
           if [ -n "$(git status --porcelain)" ]; then
             exit 1
           fi
-
-      - name: Format
-        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
 
       - name: Run test
         run: |
