chore: Use a shared test workflow.
Also
* Use the same Makefile targets as developers are using.
* Unify on-pull-request and on-oush-to-main.

diff --git a/.github/workflows/manual_release.yml b/.github/workflows/manual_release.yml
--- a/.github/workflows/manual_release.yml
+++ b/.github/workflows/manual_release.yml
@@ -22,63 +22,31 @@ jobs:
       - name: Output release
         id: release
         run: echo "::set-output name=release::${{ steps.semrel.outputs.version }}"
-  publish_golang:
-    strategy:
-      matrix:
-        go-version: [1.19.x]
-        platform: [ubuntu-latest]
-    runs-on: ${{ matrix.platform }}
-    needs: release
-    env:
-      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
-      TEST_CACHE_NAME: "client-sdk-go-test"
-    steps:
-      - name: Setup repo
-        uses: actions/checkout@v3
+  
+  test:
+    uses: ./.github/workflows/test.yml
+    secrets:
+      auth-token: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
+      secrets: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
+    with:
+      live: true
 
-      - name: Install Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: ${{ matrix.go-version }}
+  publish_golang: [test]
+    - name: Setup repo
+      uses: actions/checkout@v3
+      with:
+        token: ${{ secrets.github-token }}
 
-      - name: Format
-        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
-
-      - name: Install goimports
-        run: go install golang.org/x/tools/cmd/goimports@latest
-
-      - run: goimports -l -w $(ls -d */*/ | grep -v "internal/protos/") ./momento
-
-      - run: go mod tidy
-
-      - name: golangci-lint
-        uses: golangci/golangci-lint-action@v3
-        with:
-          version: latest
-          only-new-issues: true
-
-    # If there are any diffs from goimports or go mod tidy, fail.
-      - name: Verify no changes from goimports and go mod tidy
-        run: |
-          if [ -n "$(git status --porcelain)" ]; then
-            exit 1
-          fi
-
-      - name: Run test
-        run: |
-          go vet ./...
-          go test -v ./momento ./incubating
-
-      - name: Publish package
-        run: |
-          set -e
-          set -x
-          export MOMENTO_SDK_VERSION="${{needs.release.outputs.version}}"
-          if [ -z "$MOMENTO_SDK_VERSION"]
-          then
-            echo "Unable to determine SDK version!  Exiting!"
-            exit 1
-          fi
-          echo "MOMENTO_SDK_VERSION=${MOMENTO_SDK_VERSION}"
-          GOPROXY=proxy.golang.org go list -m github.com/momentohq/client-sdk-go@v${MOMENTO_SDK_VERSION}
-        shell: bash
+    - name: Publish package
+      run: |
+        set -e
+        set -x
+        export MOMENTO_SDK_VERSION="${{needs.release.outputs.version}}"
+        if [ -z "$MOMENTO_SDK_VERSION"]
+        then
+          echo "Unable to determine SDK version!  Exiting!"
+          exit 1
+        fi
+        echo "MOMENTO_SDK_VERSION=${MOMENTO_SDK_VERSION}"
+        GOPROXY=proxy.golang.org go list -m github.com/momentohq/client-sdk-go@v${MOMENTO_SDK_VERSION}
+      shell: bash
